import { useMemo } from "react"
import "../styles/html-result.css"
import "katex/dist/katex.min.css"
import "katex/dist/contrib/copy-tex"
import { ReaderLayout } from "../components/ReaderLayout"
import { useDocumentContext } from "@/context/DocumentContext"
import { useAudioSelector } from "@/context/AudioContext"
import { useTTSChunkDetection } from "@/hooks/use-tts-chunk-detection"
import { useWordHighlighting } from "@/hooks/use-word-highlighting"

interface Props {
  content: string
  imagesReady: boolean
  onDownload: () => void
  onReset: () => void
}

export function HtmlResultPage({
  content,
  imagesReady,
  onDownload,
  onReset,
}: Props) {
  const documentContext = useDocumentContext()
  const chunks = documentContext?.chunks ?? []
  const isEnabled = useAudioSelector((s) => s.narrator.isEnabled)
  const { handleContentClick } = useTTSChunkDetection(chunks)

  // Enable word-level highlighting during TTS playback
  useWordHighlighting()

  const htmlContent = useMemo(() => ({ __html: content }), [content])

  return (
    <ReaderLayout
      onDownload={onDownload}
      onReset={onReset}
      showThemeToggle
      showSidebar
      downloadDisabled={!imagesReady}
    >
      {/* Safe: content is generated by Marker from user's own uploaded document */}
      <div
        onClick={isEnabled ? handleContentClick : undefined}
        style={isEnabled ? { cursor: "pointer" } : undefined}
        dangerouslySetInnerHTML={htmlContent}
      />
    </ReaderLayout>
  )
}
