/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsSourceDocumentIdRouteImport } from './routes/documents/$sourceDocumentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsSourceDocumentIdRoute =
  DocumentsSourceDocumentIdRouteImport.update({
    id: '/documents/$sourceDocumentId',
    path: '/documents/$sourceDocumentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents/$sourceDocumentId': typeof DocumentsSourceDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documents/$sourceDocumentId': typeof DocumentsSourceDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documents/$sourceDocumentId': typeof DocumentsSourceDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/documents/$sourceDocumentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/documents/$sourceDocumentId'
  id: '__root__' | '/' | '/documents/$sourceDocumentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentsSourceDocumentIdRoute: typeof DocumentsSourceDocumentIdRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$sourceDocumentId': {
      id: '/documents/$sourceDocumentId'
      path: '/documents/$sourceDocumentId'
      fullPath: '/documents/$sourceDocumentId'
      preLoaderRoute: typeof DocumentsSourceDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentsSourceDocumentIdRoute: DocumentsSourceDocumentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
